from backend.repositories.user_repository import UserRepository
from backend.repositories.base import BaseRepository
from backend.repositories.uc_code_repository import UCCodeRepository
from backend.repositories.activation_repository import ActivationRepository
from backend.repositories.purchase_repository import PurchaseRepository
from backend.repositories.reward_repository import RewardRepository
from backend.repositories.discount_repository import DiscountRepository