version: '3.7'

services:
  db:
    image: postgres:15
    container_name: db-store
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 5
  app:
    build:
      context: .
    container_name: app-store
    environment:
      - DB_NAME=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - JWT_SECRET=812659050808fd763749156b9b403c46a2338f082b4cc1316d3b0ac8794937aa
      - JWT_ACCESS_TOKEN_TIME=10000
      - JWT_ALGORITHM=HS256

    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always