version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db-store
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app_network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - app
      - frontend
    networks:
      - app_network

  frontend:
    build: ./frontend
    image: zeuc-uc-bot
    container_name: content-zeuc-uc-bot
    restart: always
    stdin_open: true
    networks:
      - app_network


  app:
    build:
      context: .
    container_name: app-store
    environment:
      - DB_NAME=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - JWT_SECRET=812659050808fd763749156b9b403c46a2338f082b4cc1316d3b0ac8794937aa
      - JWT_ACCESS_TOKEN_TIME=10000
      - JWT_ALGORITHM=HS256
    depends_on:
      - db
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 
