version: '3.0'

services:
  db:
    image: postgres:15
    container_name: db-store
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: app-store
    environment:
      - DB_NAME=postgres
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres

      - JWT_SECRET=812659050808fd763749156b9b403c46a2338f082b4cc1316d3b0ac8794937aa
      - JWT_ACCESS_TOKEN_TIME=10000
      - JWT_ALGORITHM=HS256
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge