from database.repositories.rewards import RewardRepository
from database.repositories.discount_repository import DiscountRepository
from database.repositories.settigns import SettingsRepository
from database.repositories.purchase import PurchaseRepository
from database.repositories.uc_code import UCCodeRepository
from database.repositories.user import UserRepository